apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT: "3000"
  NODE_ENV: "production"
  SERVICE_NAME: "nestjs-ddd-api"
  # Database & Redis connection details (assuming internal K8s services or external endpoints)
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "nestjs_project"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  # Observability
  JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
